# Generated by Django 5.2.8 on 2025-11-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_creatorprofile_payment_setup_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='id_back_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='id_front_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='selfie_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
