# Generated by Django 5.2.8 on 2025-11-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_creatorprofile_id_back_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand_name', models.CharField(default='Milani Cosmetics', max_length=100)),
                ('cover_image', models.URLField()),
                ('video_preview_url', models.URLField(blank=True, null=True)),
                ('compensation', models.CharField(max_length=100)),
                ('slots_total', models.IntegerField(default=50)),
                ('slots_filled', models.IntegerField(default=0)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
