# Generated by Django 5.2.8 on 2025-11-23 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contentsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='video_preview_url',
            new_name='brief_pdf_url',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='compensation',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='slots_filled',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='slots_total',
        ),
        migrations.RemoveField(
            model_name='contentsubmission',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='contentsubmission',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='contentsubmission',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='payment_setup_complete',
        ),
        migrations.AddField(
            model_name='campaign',
            name='compensation_rate',
            field=models.CharField(default='$100.00', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='phase',
            field=models.CharField(default='Phase 1', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='usage_rights',
            field=models.CharField(default='+ Usage Rights', max_length=100),
        ),
        migrations.AddField(
            model_name='contentsubmission',
            name='file_type',
            field=models.CharField(default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='contract_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='product_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='tier',
            field=models.CharField(default='Muse Tier', max_length=50),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentsubmission',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='api.campaign'),
        ),
        migrations.AlterField(
            model_name='contentsubmission',
            name='content_url',
            field=models.URLField(max_length=2048),
        ),
    ]
