# Generated by Django 5.2.8 on 2025-11-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_video_preview_url_campaign_brief_pdf_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsubmission',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], default='tiktok', max_length=50),
        ),
    ]
